name: Deploy Flutter Web to Cloudflare Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Flutter SDK
        run: |
          wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.10-stable.tar.xz
          tar xf flutter_linux_3.13.10-stable.tar.xz
          echo "$PWD/flutter/bin" >> $GITHUB_PATH

      - name: Enable Web
        run: flutter config --enable-web

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ketoan-taphoa39
          directory: build/web